### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by eilvelia** [alcalyn/hex#79]
This was discussed in #73 previously.

Unsurprisingly, when the client reconnects (not considering the reload-page-on-reconnect hack), or when an event happens between the page response and websocket connection, data loss can occur.

edit: I plan to work on this.

**Comment by eilvelia** [comment]
(See also https://socket.io/docs/v4/delivery-guarantees for reference. As per this page, the default delivery guarantee is at most once, and there is no message buffer on the server.)

**Comment by alcalyn** [comment]
Seems to be a tricky problem (with lot of edge cases I mean). I don't know your plans, was thinking to:

- for move update, send 3 last moves with their move number instead of last one only, which may solve when you miss a move only (most common bug), but won't solve others cases (game finished...)
- or when you subscribe to a socket room, send game state again, to make sure you don't miss an event between api call GET /game, and next socket events. In this case, add a mechanic in `WebsocketControllerInterface` like `onRoomEnter()`

**Comment by alcalyn** [comment]
I just remember that I noted a way to reproduce the case when you miss a move update when opening a game page:

- set in `.env`: `RANDOM_BOT_WAIT_BEFORE_PLAY=500`
- create random-bot vs determinist-random-bot game with admin api endpoint (`POST /api/admin/create-ai-vs-ai`)
    - see [this endpoint](https://www.postman.com/alcalyn/hex/request/jdgt17u/create-ai-vs-ai-game?tab=body),
    - and put same admin password in your `.env` `ADMIN_PASSWORD=xxx` and in Postman "Authorization" tab
- go watch the game from the publicId you get in response

refresh until you get the error, occurs about 60% time in the second after the refresh. You can make random bot plays faster by decreasing `RANDOM_BOT_WAIT_BEFORE_PLAY`
